name: Deploy logic apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-emelie-la-weather-bangkok:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group create -l westeurope -n Emelie-rg-dev
            az deployment group create -g Emelie-rg-dev --template-file ./LogicApps/emelie-la-weather-bangkok.json --parameters ./LogicApps/emelie-la-weather-bangkok.parameters.json --parameters greetingServicePassword=${{secrets.GREETING_SERVICE_BASIC_AUTH_PASSWORD}}

  deploy-emelie-la-send-greeting-invoice-to-billing-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group create -l westeurope -n Emelie-rg-dev
            az deployment group create -g Emelie-rg-dev --template-file ./LogicApps/emelie-la-send-greeting-invoice-to-billing-service.json --parameters ./LogicApps/emelie-la-send-greeting-invoice-to-billing-service.parameters.json --parameters greetingServicePassword=${{secrets.GREETING_SERVICE_BASIC_AUTH_PASSWORD}} billingServicePassword=${{secrets.BILLING_SERVICE_PASSWORD}}

           
